pipeline{
    agent any
    stages{
        stage('Git clone'){
            steps{
                git 'https://github.com/Keerthi-Gundla/Keerthi-Gundla.github.io.git'
            }
        }
        stage('Test'){
            steps{
                echo 'Testing completed.'
            }
        }
        stage('Build'){
            steps{
                echo 'Build completed.'
            }
        }
    }
}
